# Generated by Django 3.1.4 on 2021-01-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Miasto', models.CharField(help_text='Podać miasto', max_length=25)),
                ('Lokalizacja', models.CharField(blank=True, help_text='<b>* Pole niewymagane</b><br>Podać lokalizację(np. ulica)', max_length=50)),
                ('Opis', models.TextField(help_text='Podaj dokładny opis')),
                ('Zdjęcie', models.ImageField(blank=True, help_text='<b>* Pole niewymagane</b><br>Wklej zdjęcie', upload_to='index/pictures')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Kategoria', models.CharField(choices=[('SZUKAM', 'Szukam'), ('ZNALEZIONO', 'Znaleziono'), ('ZAKOŃCZONE', 'Zakończone'), ('INNE', 'Inne')], help_text='Wybierz kategorie ogłoszenia', max_length=15)),
                ('Kontakt', models.CharField(blank=True, help_text='<b>* Pole niewymagane</b><br>Numer kontaktowy, mail itp.', max_length=30)),
                ('Akceptacja', models.CharField(blank=True, choices=[('TAK', 'Tak'), ('NIE', 'Nie')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
