# Generated by Django 3.1.4 on 2021-01-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
